version: 2
updates:
- package-ecosystem: npm
  directory: "/AdminPanel"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-amplify
    versions:
    - 3.3.15
    - 3.3.16
    - 3.3.17
    - 3.3.18
    - 3.3.19
    - 3.3.20
    - 3.3.21
    - 3.3.22
    - 3.3.23
    - 3.3.24
    - 3.3.25
    - 3.3.26
  - dependency-name: aws-amplify-react
    versions:
    - 4.2.19
    - 4.2.20
    - 4.2.21
    - 4.2.22
    - 4.2.23
    - 4.2.24
    - 4.2.25
    - 4.2.26
    - 4.2.27
    - 4.2.28
    - 4.2.29
    - 4.2.30
  - dependency-name: react
    versions:
    - 16.14.0
    - 17.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: ini
    versions:
    - 1.3.7
