project 'UnicornTrivia.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnicornTrivia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnicornTrivia
  pod 'AWSAppSync', '~> 2.6.22'

  target 'UnicornTriviaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnicornTriviaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
